# Generated by Django 5.0.6 on 2024-06-10 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toyotasite', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='color',
            name='rgb_value',
        ),
    ]
